function [InvalidPoliciesInd ValidPoliciesInd] = CheckPolicy(yVec,PolicyMatrix,economy)
%function ValidPoliciesInd = CheckPolicy(yVec,PolicyMatrix,economy)
%yVec should have same # rows as PolicyMatrix
yVec = yVec(:);
if size(PolicyMatrix,2) ~= 3
    PolicyMatrix = reshape(PolicyMatrix,[],3);
end

PolicyRows = numel(PolicyMatrix(:,1));
if numel(yVec) == 1
    yVec = repmat(PolicyRows,1);
end
    

ConditionMatrix             = [ ...
                                [1,0,0]; ...
                                [-1,0,0]; ...
                                [0,1,0]; ...
                                [0,-1,0]; ...
                                [0,0,1]; ...
                                [0,0,-1];
                                [1,1,1]    .* [-economy.Rf, economy.RtDown - economy.Rf, (1-economy.lambda-economy.Rf / economy.CurrentHWorstReturn) * economy.CurrentPt]; ...
                                [-1,-1,-1] .* [-economy.Rf, economy.RtUp   - economy.Rf, (1-economy.lambda-economy.Rf / economy.CurrentHBestReturn) * economy.CurrentPt] ...
                              ]' ;
%LHS >= RHS? 
LHSMatrix_withadj           = PolicyMatrix * ConditionMatrix;


%Everything is setup to be LEQ the RHS matrix
RHSMatrix_withadj           = zeros(PolicyRows,8);
RHSMatrix_withadj(:,2:2:8)  = -yVec * ... 
                            [ ...
                                1, ...
                                economy.Rf / (economy.Rf - economy.RtDown), ...
                                economy.Rf / (economy.CurrentPt*(-1+economy.lambda+economy.Rf / economy.CurrentHWorstReturn)), ...
                                inf ...
                            ];       
                        
RHSMatrix_withadj(:,7)      = -yVec - (PolicyMatrix(:,3)==1) * economy.lambda*economy.CurrentPt; %Not changed by adding housing returns

%A valid point meets all 8 conditions
ValidPoliciesInd            = find((sum((LHSMatrix_withadj >= RHSMatrix_withadj),2)) / 8 == 1);
InvalidPoliciesInd            = find((sum((LHSMatrix_withadj >= RHSMatrix_withadj),2)) / 8 ~= 1);